from enum import Enum


class TokenClass(Enum):

    NUM = "NUMERIC_CONSTANT"
    LIT = "LITERAL_CONSTANT"
    ID = "IDENTIFIER"
    COMMENT = "COMMENT"
    EOF = "EOF"
    RESERVED_WORD = "RESERVED_WORD"
    OPR = "RELATIONAL_OPERATOR"
    RCB = "ATTRIBUIÇÃO"
    OPM = "ARITHMETIC_OPERATOR"
    AB_P = "LEFT_PARENTHESIS"
    FC_P = "RIGHT_PARENTHESIS"
    PT_V = "SEMICOLON"
    ERROR = "ERROR"
    VIR = "COMMA"
    IGNORE = "IGNORE"